/**
 * FlashAlpha JavaScript/TypeScript SDK
 *
 * Official SDK for the FlashAlpha options analytics API.
 * https://flashalpha.com
 *
 * @example
 * import { FlashAlpha } from 'flashalpha';
 *
 * const fa = new FlashAlpha('your-api-key');
 * const data = await fa.gex('SPY');
 */

export { FlashAlpha } from './client';
export type {
  ExpirationOptions,
  FlashAlphaOptions,
  FlowBlocksOptions,
  FlowExpiryOptions,
  FlowHistoryOptions,
  FlowLeaderboardOptions,
  FlowOutliersOptions,
  FlowRecentOptions,
  FlowSignalsOptions,
  FlowSignalsSummaryOptions,
  GexOptions,
  GreeksOptions,
  HistoricalOptionQuoteOptions,
  HistoricalStockQuoteOptions,
  IvOptions,
  KellyOptions,
  OptionQuoteOptions,
  ScreenerFilter,
  ScreenerFormula,
  ScreenerGroupCondition,
  ScreenerLeafCondition,
  ScreenerOperator,
  ScreenerOptions,
  ScreenerSortSpec,
  ZeroDteOptions,
} from './client';
export {
  AuthenticationError,
  FlashAlphaError,
  NotFoundError,
  RateLimitError,
  ServerError,
  TierRestrictedError,
} from './errors';
export type {
  ZeroDteDecay,
  ZeroDteExpectedMove,
  ZeroDteExposures,
  ZeroDteFlow,
  ZeroDteHedging,
  ZeroDteHedgingBucket,
  ZeroDteLevels,
  ZeroDteLiquidity,
  ZeroDteMetadata,
  ZeroDtePinComponents,
  ZeroDtePinRisk,
  ZeroDteRegime,
  ZeroDteResponse,
  ZeroDteStrike,
  ZeroDteVolContext,
  // ── ExposureSummary ──
  ExposureSummaryExposures,
  ExposureSummaryHedgingEstimate,
  ExposureSummaryHedgingMove,
  ExposureSummaryInterpretation,
  ExposureSummaryResponse,
  ExposureSummaryZeroDte,
  // ── VRP ──
  VrpResponse,
  VrpCore,
  VrpDirectional,
  VrpTermItem,
  VrpGexConditioned,
  VrpVannaConditioned,
  VrpRegime,
  VrpStrategyScores,
  VrpMacro,
  // ── MaxPain ──
  MaxPainResponse,
  MaxPainDistance,
  MaxPainCurveRow,
  MaxPainOiRow,
  MaxPainByExpirationRow,
  MaxPainDealerAlignment,
  MaxPainExpectedMove,
  // ── StockSummary ──
  StockSummaryResponse,
  StockSummaryPrice,
  StockSummarySkew25d,
  StockSummaryIvTermItem,
  StockSummaryVolatility,
  StockSummaryOptionsFlow,
  StockSummaryInterpretation,
  StockSummaryHedgingMove,
  StockSummaryHedgingEstimate,
  StockSummaryZeroDte,
  StockSummaryTopStrike,
  StockSummaryExposure,
  StockSummaryMacroIndex,
  StockSummaryVixTermLevels,
  StockSummaryVixTermStructure,
  StockSummaryVixFutures,
  StockSummaryFearAndGreed,
  StockSummaryMacro,
  // ── Narrative ──
  NarrativeResponse,
  Narrative,
  NarrativeData,
  NarrativeOiChange,
  // ── ExposureLevels ──
  ExposureLevelsResponse,
  ExposureLevels,
  // ── PricingGreeks ──
  PricingGreeksResponse,
  PricingInputs,
  PricingFirstOrder,
  PricingSecondOrder,
  PricingThirdOrder,
  PricingAdditional,
  // ── Volatility ──
  VolatilityResponse,
  VolatilityRealizedVol,
  VolatilityIvRvSpreads,
  VolatilitySkewProfile,
  VolatilityTermStructure,
  VolatilityIvDispersion,
  VolatilityGexBucket,
  VolatilityThetaBucket,
  VolatilityPutCallByExpiry,
  VolatilityPutCallByMoneyness,
  VolatilityPutCallProfile,
  VolatilityOiConcentration,
  VolatilityHedgingScenario,
  VolatilityLiquidity,
  // ── AdvVolatility ──
  AdvVolatilityResponse,
  AdvVolatilitySviParameters,
  AdvVolatilityForwardPrice,
  AdvVolatilityTotalVarianceSurface,
  AdvVolatilityArbitrageFlag,
  AdvVolatilityVarianceSwapFairValue,
  AdvVolatilityGreekSurface,
  AdvVolatilityGreeksSurfaces,
  // ── Surface ──
  SurfaceResponse,
  // ── Exposure (GEX/DEX/VEX/CHEX) ──
  GexResponse,
  GexStrike,
  DexResponse,
  DexStrike,
  VexResponse,
  VexStrike,
  ChexResponse,
  ChexStrike,
  // ── OptionQuote (live only) ──
  OptionQuoteResponse,
  // ── StockQuote (live only) ──
  StockQuoteResponse,
  // ── PricingIv (live only) ──
  PricingIvResponse,
  PricingIvInputs,
  // ── PricingKelly (live only) ──
  PricingKellyResponse,
  PricingKellyInputs,
  PricingKellySizing,
  PricingKellyAnalysis,
  // ── Account / Reference Data / Health / Screener ──
  AccountResponse,
  TickersResponse,
  SymbolsResponse,
  OptionsMetaResponse,
  OptionsMetaExpiration,
  HealthResponse,
  ScreenerResponse,
  ScreenerMeta,
  // ── Flow (live, simulation-aware) ──
  FlowLevelsResponse,
  FlowPinRiskResponse,
  FlowPinRiskBreakdown,
  FlowSummaryResponse,
  FlowOiResponse,
  FlowGexResponse,
  FlowDexResponse,
  FlowDealerRiskResponse,
  FlowAdjustedDealerRisk,
  FlowLiveResponse,
  FlowOptionTrade,
  FlowOptionRecentResponse,
  FlowOptionSummaryResponse,
  FlowOptionBlock,
  FlowOptionBlocksResponse,
  FlowOptionHistoryBucket,
  FlowOptionHistoryResponse,
  FlowCumulativePoint,
  FlowOptionCumulativeResponse,
  FlowStockTrade,
  FlowStockRecentResponse,
  FlowStockSummaryResponse,
  FlowStockBlock,
  FlowStockBlocksResponse,
  FlowStockHistoryBucket,
  FlowStockHistoryResponse,
  FlowStockCumulativeResponse,
  FlowOptionLeaderRow,
  FlowOptionLeaderboardResponse,
  FlowOutlierRow,
  FlowOptionOutliersResponse,
  FlowStockLeaderRow,
  FlowStockLeaderboardResponse,
  FlowStockOutliersResponse,
  FlowSignalsChain,
  FlowSignalScoreBreakdown,
  FlowSignalEnrichment,
  FlowSignal,
  FlowSignalsResponse,
  FlowSignalsSummaryResponse,
  // ══ v1.1 additions ══
  // ── Strategy signals (shared StrategyDecisionResponse envelope) ──
  StrategyStructureLeg,
  StrategyBestStructure,
  StrategyRiskFlag,
  StrategyDataQuality,
  StrategyDecisionResponse,
  StrategyExpiryOptions,
  StrategyExpiryPositioningOptions,
  StrategyZeroDteOptions,
  StrategyVolCarryOptions,
  StrategyYieldEnhancementOptions,
  // ── SVI surface ──
  SurfaceSviSlice,
  SurfaceSviResponse,
  // ── Expected move ──
  ExpectedMoveItem,
  ExpectedMoveResponse,
  ExpectedMoveOptions,
  // ── Exposure sheet ──
  ExposureSheetTotals,
  ExposureSheetLis,
  ExposureSheetPeak,
  ExposureSheetStrike,
  ExposureSheetResponse,
  ExposureSheetOptions,
  // ── Exposure term structure ──
  ExposureTermStructureBucket,
  ExposureTermStructureExpiry,
  ExposureTermStructureResponse,
  // ── Exposure basket ──
  ExposureBasketAggregate,
  ExposureBasketConstituent,
  ExposureBasketResponse,
  ExposureBasketOptions,
  // ── OI diff ──
  OiDiffChange,
  OiDiffResponse,
  OiDiffOptions,
  // ── Liquidity ──
  LiquidityExpiry,
  LiquidityResponse,
  // ── Skew term ──
  SkewTermExpiry,
  SkewTermResponse,
  // ── Spot/vol correlation ──
  SpotVolCorrelationResponse,
  // ── Dispersion ──
  DispersionContributor,
  DispersionResponse,
  DispersionOptions,
  // ── Realized volatility ──
  RealizedVolatilityWindow,
  RealizedVolatilityResponse,
  // ── Volatility forecast ──
  VolatilityForecastEwma,
  VolatilityForecastHarComponents,
  VolatilityForecastHarRv,
  VolatilityForecastGarchParams,
  VolatilityForecastGarchPoint,
  VolatilityForecastGarch,
  VolatilityForecastResponse,
  VolatilityForecastOptions,
  // ── VIX state / Universe ──
  VixStateResponse,
  UniverseSymbol,
  UniverseResponse,
  UniverseOptions,
  // ── Flow: dealer premium ──
  FlowDealerPremiumResponse,
  FlowDealerPremiumOptions,
  // ── Zero-DTE flow ──
  ZeroDteFlowDirection,
  ZeroDteFlowSnapshotResponse,
  ZeroDteFlowSeriesBar,
  ZeroDteFlowSeriesResponse,
  ZeroDteFlowSeriesOptions,
  ZeroDteHedgeFlowBar,
  ZeroDteHedgeFlowResponse,
  ZeroDteHedgeFlowOptions,
  ZeroDteHeatmapBar,
  ZeroDteHeatmapResponse,
  ZeroDteHeatmapOptions,
  ZeroDteStrikeFlowBar,
  ZeroDteStrikeFlowResponse,
  ZeroDteStrikeFlowOptions,
  // ── Flow: stock bars ──
  FlowStockBar,
  FlowStockBarsResponse,
  FlowStockBarsOptions,
  // ── VRP history / options ──
  VrpHistoryItem,
  VrpHistoryResponse,
  VrpHistoryOptions,
  VrpOptions,
  // ── Earnings ──
  EarningsCalendarEvent,
  EarningsCalendarResponse,
  EarningsCalendarOptions,
  EarningsExpectedMoveBlock,
  EarningsExpectedMoveResponse,
  EarningsHistoryItem,
  EarningsHistoryResponse,
  EarningsHistoryOptions,
  EarningsIvCrushEstimate,
  EarningsIvCrushDistribution,
  EarningsIvCrushResponse,
  EarningsVrpBlock,
  EarningsSurpriseReaction,
  EarningsVrpResponse,
  EarningsDealerLevels,
  EarningsDealerGexBucket,
  EarningsDealerTopStrike,
  EarningsDealerPositioningResponse,
  EarningsStrategyScores,
  EarningsStrategyContext,
  EarningsStrategiesResponse,
  EarningsScreenerEvent,
  EarningsScreenerResponse,
  EarningsScreenerOptions,
  // ── Structures (POST) ──
  StructureLeg,
  StructurePnlRequest,
  StructurePnlPoint,
  StructurePnlResponse,
  StructureGreeksLeg,
  StructureGreeksRequest,
  StructurePositionGreeks,
  StructureGreeksResponse,
  // ── Screener fields ──
  ScreenerField,
  ScreenerFieldsResponse,
} from './types';
